
columns:
  location_ID:
    value_type: id
    describes: location
    default: __AUTO__  # we'll generate one but for consistency it's better if providers provide

  collection_ID:
    value_type: id
    describes: collection

  sample_ID:
    value_type: id
    describes: sample

  collection_raw_dates:
    required: false
    value_type: string # this won't be validated, even when we actually do date validation (issue #6)
    describes: collection
    multi-valued: false # values are likely to contain semicolons, but make sure we don't treat them as multi-valued 
    column_term: OBI_0001619
    description: multiple semicolon-delimited dates (DATE = YYYY, YYYY-MM or YYYY-MM-DD) and/or date ranges (DATE/DATE)
    
  collection_start_date:
    value_type: date
    describes: collection
    column_term: EUPATH_0043256

  collection_end_date:
    value_type: date
    describes: collection
    column_term: EUPATH_0043257
    required: false
    comment: use the `collection_duration` column to specify duration in days if not 1

  trap_ID:
    value_type: string # not `id` because trap is not one of our core entity types 
    describes: collection
    required: false
    column_term: POPBIO_8000007

  GPS_latitude:
    value_type: latitude
    describes: location
    column_term: OBI_0001620

  GPS_longitude:
    value_type: longitude
    describes: location
    column_term: OBI_0001621

  GPS_qualifier:
    value_type: string
    describes: location
    required: false
    deprecated: use location_precision and location_provenance instead

  location_precision:
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    column_term: EUPATH_0043212

  location_provenance:
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    column_term: EUPATH_0043211

  location_description:
    value_type: string
    describes: location
    required: false
    column_term: EUPATH_0000542

  location_country:
    value_type: string
    describes: location
    required: false
    column_term: OBI_0001627

  location_ADM1:
    value_type: string
    describes: location
    required: false
    column_term: ENVO_00000005

  location_ADM2:
    value_type: string
    describes: location
    required: false
    column_term: ENVO_00000006

  trap_type:
    value_type: string
    describes: collection
    required: false
    deprecated: use collection_method and collection_device instead

  collection_method:
    value_type: protocol_ref
    describes: collection
    
  collection_device:
    value_type: term
    describes: collection
    required: false
    column_term: OBI_0000968

  attractant:
    value_type: term
    describes: collection
    required: false
    multivalued: true
    column_term: EUPATH_0043001

  trap_number:
    value_type: number
    describes: collection
    default: 1
    description: the number of traps, not an ID number!
    column_term: EUPATH_0043046

  trap_duration:
    value_type: number
    describes: collection
    required: false
    deprecated: use collection_duration instead

  collection_duration:
    value_type: number
    describes: collection
    default: 1
    description: duration of collection in days
    column_term: OBI_0002988
    
  species:
    value_type: term
    term_lookup: study_species
    describes: organism identification assay
    column_term: EUPATH_0043194

  species_identification_method:
    value_type: protocol_ref
    describes: organism identification assay

  developmental_stage:
    value_type: term
    term_lookup: study_developmental_stages
    describes: sample
    column_term: UBERON_0000105

  combined_feeding_and_gonotrophic_status:
    value_type: term
    term_lookup: study_terms
    describes: sample
    required: false
    column_term: EUPATH_0043227

  sex:
    value_type: term
    term_lookup: study_sexes
    describes: sample
    column_term: PATO_0000047

  sample_count:
    value_type: number
    describes: sample
    column_term: EUPATH_0043155
    
  location_comment:
    value_type: comment
    describes: location
    required: false

  collection_comment:
    value_type: comment
    describes: collection
    required: false

  sample_comment:
    value_type: comment
    describes: sample
    required: false

  species_comment:
    value_type: comment
    describes: organism identification assay
    required: false

  sample_method:
    value_type: protocol_ref
    describes: sample
    default: PORTIONING

  sample_type:
    value_type: term
    describes: sample
    default: pool
    column_term: EUPATH_0000611

  phenotypes:
    value_type: string
    describes: pathogen detection assay
    required: false
    deprecated: not implemented yet - use wide columns instead?


  # to do? add pathogen_comment, insecticide_resistance_comment etc?

  
#
# default protocol for `sample_method`
# we could add more default protocols if we like?
#
default_study_protocols:
  - study_protocol_name : PORTIONING 
    study_protocol_type : material portioning
    study_protocol_type_term_source_ref : EUPATH
    study_protocol_type_term_accession_number : OBI_0600018


location_qualifiers:
  # location was looked up at following levels (rather than taken from a device)
  country_level : EUPATH_0043241
  adm1_level : EUPATH_0043242
  adm2_level : EUPATH_0043243


#
# provide the basic terms needed for defaults
#
study_terms:
  pool: OBI_0302716


#
# used internally - unlikely to need overriding
#
study_assay_measurement_type_term_lookup:
  organism identification assay: OBI_0001624
  blood meal assay: OBI_0002732
  pathogen detection assay: OBI_0002728
  insecticide resistance assay: OBI_0002695
  genotyping assay: OBI_0000435


