# TO DO:
# refactor this to hash of hashes (I did the first couple)
# this allows us to merge the user's config file with the default config file with ease

columns:
  location_ID:
    value_type: id
    describes: location

  collection_ID:
    value_type: id
    describes: collection

  sample_ID:
    value_type: id
    describes: sample

  collection_start_date:
    value_type: date
    describes: collection
    column_term: EUPATH_0043256

  collection_end_date:
    value_type: date
    describes: collection
    column_term: EUPATH_0043257


  trap_ID:
    value_type: string # not `id` because trap is not one of our core entity types 
    describes: collection
    required: false
    column_term: POPBIO_8000007

  GPS_latitude:
    value_type: latitude
    describes: location
    column_term: OBI_0001620

  GPS_longitude:
    value_type: longitude
    describes: location
    column_term: OBI_0001621

  GPS_qualifier:
    value_type: string
    describes: location
    deprecated: use location_precision and location_provenance instead

  location_precision:
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    column_term: EUPATH_0043212

  location_provenance:
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    column_term: EUPATH_0043211

  location_description:
    value_type: string
    describes: location
    required: false
    column_term: EUPATH_0000542

  location_country:
    value_type: string
    describes: location
    required: false
    column_term: OBI_0001627

  location_ADM1:
    value_type: string
    describes: location
    required: false
    column_term: ENVO_00000005

  location_ADM2:
    value_type: string
    describes: location
    required: false
    column_term: ENVO_00000006

  trap_type:
    value_type: string
    describes: collection
    required: false
    deprecated: use collection_method and collection_device instead

  collection_method:
    value_type: string



location_qualifiers:
  abc : DEF_0123456

