# TO DO:
# refactor this to hash of hashes (I did the first couple)
# this allows us to merge the user's config file with the default config file with ease

columns:
  location_ID:
    value_type: id
    describes: location

  collection_ID:
    value_type: id
    describes: collection

  sample_ID:
    value_type: id
    describes: sample

  # TO DO THE REST...
  - heading: collection_start_date
    value_type: date
    describes: collection
    term: EUPATH_0043256

  - heading: collection_end_date
    value_type: date
    describes: collection
    term: EUPATH_0043257

# not `value_type: id` because trap is not one of our core entity types 
  - heading: trap_ID
    value_type: string
    describes: collection
    required: false
    term: POPBIO_8000007

  - heading: GPS_latitude
    value_type: latitude
    describes: location
    term: OBI_0001620

  - heading: GPS_longitude
    value_type: longitude
    describes: location
    term: OBI_0001621

  - heading: GPS_qualifier
    value_type: string
    describes: location
    deprecated: use location_precision and location_provenance instead

  - heading: location_precision
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    term: EUPATH_0043212

  - heading: location_provenance
    value_type: term
    term_lookup: location_qualifiers
    describes: location
    required: false
    term: EUPATH_0043211

  - heading: location_description
    value_type: string
    describes: location
    required: false
    term: EUPATH_0000542

  - heading: location_country
    value_type: string
    describes: location
    required: false
    term: OBI_0001627

  - heading: location_ADM1
    value_type: string
    describes: location
    required: false
    term: ENVO_00000005

  - heading: location_ADM2
    value_type: string
    describes: location
    required: false
    term: ENVO_00000006

  - heading: trap_type
    value_type: string
    describes: collection
    required: false
    deprecated: use collection_method and collection_device instead

  - heading: collection_method
    value_type: string



location_qualifiers:
  abc : DEF_0123456

