columns:
  - heading: location_ID
    type: id
    describes: location

  - heading: collection_ID
    type: id
    describes: collection

  - heading: sample_ID
    type: id
    describes: sample

  - heading: collection_start_date
    type: date
    describes: collection
    term: EUPATH_0043256

  - heading: collection_end_date
    type: date
    describes: collection
    term: EUPATH_0043257

# not `type: id` because trap is not one of our core entity types 
  - heading: trap_ID
    type: string
    describes: collection
    controlled: false
    required: false
    term: POPBIO_8000007

  - heading: GPS_latitude
    type: latitude
    describes: location
    term: OBI_0001620

  - heading: GPS_longitude
    type: longitude
    describes: location
    term: OBI_0001621

  - heading: GPS_qualifier
    type: string
    describes: location
    controlled: false
    deprecated: use location_precision and location_provenance instead

  - heading: location_precision
    type: string
    describes: location
    required: false
    term: EUPATH_0043212

  - heading: location_provenance
    type: string
    describes: location
    required: false
    term: EUPATH_0043211

  - heading: location_description
    type: string
    describes: location
    required: false
    controlled: false
    term: EUPATH_0000542

  - heading: location_country
    type: string
    describes: location
    required: false
    controlled: false
    term: OBI_0001627

  - heading: location_ADM1
    type: string
    describes: location
    required: false
    controlled: false
    term: ENVO_00000005

  - heading: location_ADM2
    type: string
    describes: location
    required: false
    controlled: false
    term: ENVO_00000006

  - heading: trap_type
    type: string
    describes: collection
    required: true
    deprecated: use collection_method and collection_device instead


