study_identifier : 2023-saf2-demo
study_title : Example study title
study_submission_date : 2023
study_description : Example study description

# TO DO: publications and contacts

study_species:
  Anopheles darlingi: NCBITaxon_43151
  Anopheles albimanus: NCBITaxon_7167

study_sexes:

study_developmental_stages:

study_terms:
  shannon: OBI_0002942 # Shannon trap
  hay: EUPATH_0043004
  CO2: CHEBI_16526

columns:
# switch off some mandatory columns while developing
  developmental_stage:
    required: false

  sex:
    required: false

  sample_count:
    required: false

study_protocols:
  - study_protocol_name : COLLECT
    study_protocol_type : citizen science collection
    study_protocol_type_term_source_ref : EUPATH
    study_protocol_type_term_accession_number : EUPATH_0043237
    study_protocol_description : Residents of the state of Maine, USA, sent in ticks they find (usually on themself) to a central laboratory for analysis.

  - study_protocol_name : PCR
    study_protocol_type : organism identification by PCR assay
    study_protocol_type_term_source_ref : EUPATH
    study_protocol_type_term_accession_number : OBI_0002740
    study_protocol_description : Do PCR with diagnostic primers to find out the species
