study_identifier : 2023-saf2-demo
study_title : Example study title
study_submission_date : 2023
study_description : Example study description

# TO DO: publications and contacts

study_species :
  Anopheles darlingi : NCBITaxon_43151
  Anopheles albimanus : NCBITaxon_7167

columns:
# switch off some mandatory columns while developing
  trap_type:
    required: false

  trap_number:
    required: false

  trap_duration:
    required: false

  developmental_stage:
    required: false

  sex:
    required: false

  sample_count:
    required: false



