study_identifier : 2023-t0-poc
study_title : Transmission Zero proof of concept
study_submission_date : 2023
study_description : Here we aim to link multiple, orthogonal datasets in time and space.

default_study_protocols:
  - study_protocol_name : LINKING
    study_protocol_type : spatio-temporal binning
    study_protocol_type_term_source_ref : TERM
    study_protocol_type_term_accession_number : FIELD_0000012

columns:

  ### LINKER ###
  linker_ID:
    value_type: id
    describes: linker

  linker_geohash:
    value_type: string
    describes: linker
    column_term: FIELD_0000008

  linker_latitude:
    value_type: latitude
    describes: linker
    column_term: OBI_0001620

  linker_longitude:
    value_type: longitude
    describes: linker
    column_term: OBI_0001621

  linker_period:
    value_type: string
    describes: linker
    column_term: FIELD_0000009

  ### ADULT ENTOMOLOGY ###
  adult_ento_ID:
    value_type: id
    describes: adult entomology collection
    default: __AUTO__

  adult_ento_protocol:
    value_type: protocol_ref
    describes: adult entomology collection
    default: LINKING

## TO DO: add to SimpleAbundanceFormat repo in new configs directory ##
  ento_site_name:
    value_type: string
    describes: entomology
    column_term: MULTI_0000013
    required: false

  ento_latitude:
    value_type: latitude
    describes: entomology
    column_term: OBI_0001620
    required: false

  ento_longitude:
    value_type: longitude
    describes: entomology
    column_term: OBI_0001621
    required: false

  ento_date:
    value_type: date
    describes: entomology
    column_term: MULTI_0000006
    required: false

  sample_ID:
    value_type: id
    describes: sample
    required: false
    
  sample_protocol:
    value_type: protocol_ref
    describes: sample
    default: PORTIONING

  species:
    value_type: string
    describes: sample
    column_term: MULTI_0000007
    required: false

  count:
    value_type: number
    describes: sample
    column_term: MULTI_0000008
    required: false

  epi_ID:
    value_type: id
    describes: epidemiology
    required: false

  epi_protocol:
    value_type: protocol_ref
    describes: epidemiology
    default: EPI

  clinic_name:
    value_type: string
    describes: epidemiology
    column_term: MULTI_0000009
    required: false

  clinic_place:
    value_type: string
    describes: epidemiology
    column_term: MULTI_0000010
    required: false

  clinic_date:
    value_type: date
    describes: epidemiology
    column_term: MULTI_0000011
    required: false

  epi_latitude:
    value_type: latitude
    describes: epidemiology
    column_term: OBI_0001620
    required: false

  epi_longitude:
    value_type: longitude
    describes: epidemiology
    column_term: OBI_0001621
    required: false

  malaria_cases:
    value_type: number
    describes: epidemiology
    column_term: MULTI_0000012
    required: false

