- name: linker
  type: material
  isa_key: sources
  isa_material_type:
    value: event linker
    term_source_ref: TERM
    term_accession_number: FIELD_0000001

  children:
    - name: adult entomology collection
      type: material
      isa_key: samples
      isa_material_type:
        value: adult entomology collection
        term_source_ref: TERM
        term_accession_number: FIELD_0000002

      children:
        - name: adult entomology sample
          type: material
          isa_key: samples
          isa_material_type:
            value: adult entomology sample
            term_source_ref: TERM
            term_accession_number: FIELD_0000003

    - name: larval entomology collection
      type: material
      isa_key: samples
      isa_material_type:
        value: larval entomology collection
        term_source_ref: TERM
        term_accession_number: FIELD_0000004

      children:
        - name: larval entomology sample
          type: material
          isa_key: samples
          isa_material_type:
            value: larval entomology sample
            term_source_ref: TERM
            term_accession_number: FIELD_0000005

    - name: epidemiology event
      type: material
      isa_key: samples
      isa_material_type:
        value: epidemiology event
        term_source_ref: TERM
        term_accession_number: FIELD_0000006

      children:
        - name: epidemiology result
          type: material
          isa_key: samples
          isa_material_type:
            value: epidemiology result
            term_source_ref: TERM
            term_accession_number: FIELD_0000007
